---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: quote
    spec:
      containers:
        - name: quote
          # image: docker.io/datawire/quote:0.4.1
          image: 498849585827.dkr.ecr.us-east-1.amazonaws.com/portfolio:latest
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 250m
              memory: 250Mi
            limits:
              cpu: 400m
              memory: 400Mi
        
